language: python
python:
  #  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"


os: linux
# Ubuntu 14.04 Trusty support
#sudo: required
#dist: trusty
# install new cmake
#addons:
#  apt:
#    packages:
#      - cmake
#    sources:
#      - kalakris-cmake
env:
  # - CONDA_PYTHON_VERSION=2.7
  - CONDA_PYTHON_VERSION=3.6
  - CONDA_PYTHON_VERSION=3.7

services:
  - xvfb
#virtualenv:
#  system_site_packages: true
before_script:
    # GUI
    - "export DISPLAY=:99.0"
#    - "sh -e /etc/init.d/xvfb start"
#    - sleep 3 # give xvfb sume time to start

before_install:
  - wget https://raw.githubusercontent.com/mjirik/discon/master/tools/install_conda.sh && source install_conda.sh
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  # - if [[ "$CONDA_PYTHON_VERSION" == "2.7" ]]; then
  #     echo "python 2"
  #   else
  #     echo "python 3"
  #   fi
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels mjirik
  - conda config --add channels conda-forge
  - conda config --add channels SimpleITK
  #    - conda config --add channels luispedro
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

#    - sudo apt-get install -qq cmake libinsighttoolkit3-dev libpng12-dev libgdcm2-dev
    # - wget http://147.228.240.61/queetech/sample-extra-data/io3d_sample_data.zip && unzip io3d_sample_data.zip
# command to install dependencies
install:
  - conda create --yes -n travis python=$CONDA_PYTHON_VERSION
  - source activate travis
  #    - Install dependencies
  - conda install --yes --file requirements_conda.txt pytest-cov coveralls

# command to run tests
script: python -m pytest --cov=teigen/
after_success:
    - coveralls
