package:
  name: teigen
  version: "0.2.4"

source:
# this is used for build from git hub
  git_rev: 0.2.4
  git_url: https://github.com/mjirik/teigen.git

# this is used for pypi
  # fn: io3d-1.0.30.tar.gz
  # url: https://pypi.python.org/packages/source/i/io3d/io3d-1.0.30.tar.gz
  # md5: a3ce512c4c97ac2410e6dcc96a801bd8
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    - teigen = teigen:main
    #
    # Would create an entry point called io3d that calls io3d.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
#    - collections
    - vtk
    - io3d
    - numpy
    - scipy
    - scikit-image
    - ndnoise
    - imtools
#    - pyqt 4.11.*

  run:
    - python
#    - collections
    - vtk
    - io3d >=1.1.16
    - numpy
    - scikit-image
    - pyqt 4.11.*
    - pyqtconfig
    - pandas
    - simpleitk
    - imtools >=0.2.4
    - gensei
    - pyqtgraph
    - git # kvuli instalaci gensei
    - ndnoise >=0.0.8

test:
  # Python imports
  imports:
    - teigen

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mjirik/disco
  license: Apache v2
  summary: 'Test Image Generator'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
